### ISSUE TITLE
How to Filter Missing JSON Elements in R

### ISSUE THREAD

**Issue by rebarton** [USEPA/cam-api-examples#5]
R/JSON/Github newbie.. I am trying to extract details of the various types of monitoring equipment used to measure emissions on power plant stacks (manufacturer, model, type).

This information is contained within the "monitoringSystems" element of the JSON object. However, some of these power plants do not use monitoring equipment on their stacks and there is no "monitoringSystems" element.

If I run my script without attempting to filter units without monitoring systems, I get the following error (locName is an element of monitoringSystems, which doesn't exist for index=3):

Caused by error in map(): ℹ In index: 3. Caused by error in dplyr::select(): ! Can't subset columns that don't exist. ✖ Column locName doesn't exist.

I tried skipping those units without a monitoringSystems element using an 'if exists' function, but I get the following error:

Error in mutate(): ! Problem while computing response = get_monitor_data(query). Caused by error in map(): ℹ In index: 1. Caused by error in if (.) ...: ! the condition has length > 1

Here's the a portion of the code that I received from CAM tech support for retrieving other data that I modified for this purpose:

**get_monitor_data <- function(queries) {
  response <- queries %>%
   map(function(query){
     response <- GET(query)
     warn_for_status(response)
     if (response$status_code == 200) {
       mon_json <- content(response, as = "text")
       units_tbl <- mon_json %>%
         enter_object("data") %>%
         spread_all() %>%
         enter_object("monitoringLocations") %>%
         gather_array() %>%
         spread_all() %>%
         
     if(exists("monitoringSystems")) {

         enter_object(monitoringSystems) %>%
         gather_array() %>%
         spread_all() %>%
            
       select(
            LOC_NAME = locName,
        SYS_ID = sysId,
        SYS_TYPE_CODE = sysTypeCode,
        COMPONENT_ID = componentId,
        SERIAL_NUM = serialNum,
        MANUFACTURER = manufacturer,
        MODEL_VERSION = modelVersion,
        COMPONENT_TYPE_CODE = componentTypeCode,
        ACQ_CODE = acqCode,
        BASIS_CODE = basisCode,
        SYS_BEGIN_DATE_HOUR = sysBeginDateHour,
        SYS_END_DATE_HOUR = sysEndDateHour,
        COMPONENT_BEGIN_DATE_HOUR = componentBeginDateHour,
        COMPONENT_END_DATE_HOUR = componentEndDateHour,
        SYSTEM_TYPE_DESCRIPTION = systemTypeDescription,
        SYSTEM_DESIGNATION_CODE_DESC = systemDesignationCodeDesc,
        ACQ_CODE_DESCRIPTION = acqCodeDescription,
        COMPONENT_TYPE_CODE_DESCRIPTION = componentTypeCodeDescription,
        BASIS_CODE_DESC = basisCodeDesc
         )
       }      
     }
    }
   )
}

Perform the GET request for each query and pull out the content of the request, and gather the laod dater for each unit.

#Pull out the content of the request
responses <- queries %>%
  mutate(
    response = get_monitor_data(query)
    )

#Unnest the data frames from the response
unit_monitor_data <- unnest(responses, cols = c(response))

unit_monitor_data**

**Comment by kstetsyuk** [comment]
Hello! Apologies on a late response. Do you still need help with this issue?

**Comment by rebarton** [comment]
No problem.  I appreciate the response.  I could definitely still use some help.  Thanks!

Rob Barton
RTP Environmental Associates, Inc.
304-A West Millbrook Road
Raleigh, NC  27609
Office # 919-845-1422 ext. 24
Cell # 919-308-7701

**Comment by kstetsyuk** [comment]
Which API and endpoint are you trying these queries on?
