### ISSUE TITLE
api key not working

### ISSUE THREAD

**Issue by bbordine** [USEPA/cam-api-examples#9]
I navigated to the link in the documentation, https://www.epa.gov/airmarkets/cam-api-portal#/api-key-signup, and very quickly received an email with an api key from the email adddress noreply@api.data.gov. After entering the api key into my local copy of the script bulk_data_api_demo.py, I receive an error message:
`Error message: An invalid api_key was supplied. Get one at https://api.epa.gov:443
`
The error message url returns a page saying 'Sorry, but this web page does not exist.'

**Comment by bbordine** [comment]
Oh boy I resolved that just now, and it was due to user error on my part. It would still be worth updating the error message to supply a working link for api signup.

**Comment by kstetsyuk** [comment]
Hey @bbordine ! Thanks for the note. We'll get this fixed!
